baseURL = "https://blog.billzhuang.com/"
languageCode = "en-us"
title = "Bill's Blog"
theme = "m10c"

[params]
  author = "Bill Zhuang"
  description = "Bill is a freelancer to build software"
  avatar = "https://i.loli.net/2019/10/01/P2hc9v4OaJwkobM.jpg"
